* *
** ?
**** Say no to cheap dopamine. Don't sell yourself to pleasure. 
What is the syllogistic structure?
Cheap dopamine: to give in to the short term desires is one way cheap dopamine manifests itself.
What is captured in saying no to cheap dopamine that is not captured in saying yes to long term over short term?
**** resistance compounds, don't let it. Only good routines. Say no to bad routines.
how do I make this actionable
**** what is fomo? opportunity cost; unclear understanding of the big picture; greed (for you ought to stay in your circle of competence)
**** Why can't I say no to a good conversation? When does it start being a problem? Why is it not a problem until it is not a problem?
I derive value from a good conversation. You stick with the good conversation, because there is no clear instruction. You could also do this and that is why you do this. If you had a clear instruction and clear consequence of skipping on work, then you would not skip on that work. On the other hand, the issue is 
I think a huge part of what affects my behaviour is serendipity. That I would claim is greedy. For serendipity by definition is that which is not planned. So if you have a plan, you go with it and if things still happen, you call that serendipity.
**** staying in your circle of competence does not sit very well with get out of your comfort zone.
**** determining precedence of principles
***** example: 
****** before class work or after class work? before class work.
****** to work for a far off deadline or to not. Why have I not wanted to work for a far of deadline? Conversation, investing in people. Fellow humans first, but I think I am discovering a limiting point here.
******* coversation is not quite it. It is about desire to either come closer to or move away from a person. more pertinent is the desire to move closer to a person. When ought one invest energy-time in coming closer to a person. The idea is two fold. One ought to invest energy-time in a person when you need a nbreak from work and when it is serendipitous. Serendipitous conversations are more organic and thus more suitable in spending quality time that builds trust, the basis of a dynamic. Trust accelerates cooperation and so is a very valuable thing to invest in. Serendipitous conversation takes precedence but over what? It takes precedence over a far off deadline and herein lies the issue. The issue then actually lies in two errors:
******** error 1: you have not scheduled sub-works for the far off deadline. You are doing work and it takes time. Cut yourself some slack. 
******** revelation: god is in the details, small work is where compounding happens. Continuous work will yield you a no stress life, in the limit. Only when you respect your own schedule will other respect your schedule. You can be elegant and sweet and wonderful even on a busy schedule and people will respect you far more for it. YOu don't have to tell the other person what work it is you are doing. 'I am occupied' will do, really.
******** opportunity: deftly rescheduling is in agreement with 'create longing through absence' principle of Mr Greene.


**** How does one stay averse to inaction?

**** the practice of silence

** .
*** principle-set
**** first rule of the principle set is that you follow your principles
**** accountability, and ownership of work.
**** long term over short term, in the limit, any day.
***** Hell yeah or no is a way to achieve this.
**** humility is a non-negotiable, for it is not for others, it is for your own self
humility is among other things a way of emptying the cup of your being, so that there is room for more from the world.
**** always only lead by example
**** no conspicuous consumption
**** no substances
**** no task-switching (aka multi-tasking)
**** Each new day, earn your own success. Don't live off of yesterday.
**** endogenic highs and lows only, paleolithic diet, embracing boredom
***** it is important to see the lows through, it builds character.
***** What you do as a response to boredom determines your life to some extent. ~ Dan Koe (youtube productivity guy).
**** meditation and friendship are like insurance. Pay your premiums. 
**** focus on things in your control
**** focus on work
**** don't celebrate; celebrate only when
this is in line with dopamine graph and baseline resetting. when you celebrate you are embodying the idea in your dopamine release, that whatever you have done albeit worth desriable is also rare. When something is achieved, while others celebrate, you ought to act with nonchalance and realise that you are now that sort of person that just does this thing that is achieved in a commonplace manner.
celebrate when there is an utter lack of motivation. Do a small achievable task and celebrate it in your dopaminergic way, then this will trigger a cycle of dopamine release and work that will carry you.
**** Never complain, never explain
never complain that life is a certain way, focus on your work and things in your control. Never explain for saying sorry is not desirable for it makes the dissonance go away, you want the dissonance to stay with you as a negative feedback, never explain your actions, if you are sorry, show it in your future actions by not doing it again, never explain yourself, time will show everything to everyone, focus on just doing your work and abiding by your principles.

**** never seek a piece of advice, for advice is a monologic discourse, have a conversation with people to understand what they did or would do, to understand their operating priniciples, in this discourse, there happens a dialogue and through that something useful, such as knowledge or insight, may emerge.
**** focus, unwavering attention.
**** cue-stimulus-routine, golden rule of habit change. If you have started a bad routine, the simple way out is to do what would the good routine upon encounting the cue.
**** Amor Fati
**** sharpen your axe before you swing it.
**** don't interrupt the daemon (creative spirit) (daemon as talked about eat pray love author Elizabeth Gilbert in her ted talk). Let the daemon (creative spirit)  interrupt and take over
**** If it is for a principle, bend a knee, take a loss. But also remember, in the limit, you take no loss; if it appears otherwise, reevaluate your principle set.
**** precedence rules for work
***** Reading up before class >>>(is so much better and desirable than) reading after class

**** A stitch in time saves nine. A stitch well in advance will save nine million.

**** social interface as blog to save energy, time and opportunity cost.

****  skeletal muscle is a reservoir of blood glucose [andrew huberman podcast]. it is important to prioritize long term over short term. thus, building and maintaining skeletal muscle is important.

**** say no to cheap dopamine. do not sell yourself to pleasure.

** ""
** _
