* *
** clashes, queries and staged ideas that are being workshopped
**** resistance compounds, don't let it. Only good routines. Say no to bad routines.
***** how do I make this actionable
****** when there is resistance, reorient your response to the stimulus in whatever capacity you can, upto the point that resistance overwhelms you and no more beyond. This enables you to reproduce the response again next time you encounter the stimulus and over time the resistance will wither away or crumble down. Comes under response-stimulus management.
****** how do i say no to bad routines? Taking it one step at a time is one thing, but another thing is to identify the stimuli themselves and make sure they do not resurface or at least not resurface in the same form.
**** measure. What gets measured, gets done. That which is measured, improves.
***** Proposal to split the 10 hours of the week into class hours (4), review and flesh out hours (2), write hours (2), edit et al hours (2). Approved!
**** what is fomo? opportunity cost; unclear understanding of the big picture; greed (for you ought to stay in your circle of competence)
**** 'staying in your circle of competence' does not sit very well with 'get out of your comfort zone'. The synthesis comes in the form of finding the right amount of challenge. But that is not what Warren is talking about. Well, perhaps, then, another part of the synthesis is to try and unify everything you find and use them to inform the thing that is your circle of competence.
**** determining precedence of principles
***** example: 
****** before class work or after class work? before class work.
****** to work for a far off deadline or to not. Why have I not wanted to work for a far of deadline? Conversation, investing in people. Fellow humans first, but I think I am discovering a limiting point here.
******* coversation is not quite it. It is about desire to either come closer to or move away from a person. more pertinent is the desire to move closer to a person. When ought one invest energy-time in coming closer to a person. The idea is two fold. One ought to invest energy-time in a person when you need a nbreak from work and when it is serendipitous. Serendipitous conversations are more organic and thus more suitable in spending quality time that builds trust, the basis of a dynamic. Trust accelerates cooperation and so is a very valuable thing to invest in. Serendipitous conversation takes precedence but over what? It takes precedence over a far off deadline and herein lies the issue. The issue then actually lies in two errors:
******** Why can't I say no to a good conversation? Because we 'don't interrupt the daemon'. When does it start being a problem? Why is it not a problem until it is not a problem? It is not a problem until it is, because until it becomes a problem, I continue invite unplanned goodness into my life. This is the 'engagment with unknown unknowns', which is highly valued. It is important for me 'lend myself' to it.
******** error 1: you have not scheduled sub-works for the far off deadline. You are doing work and it takes time. Cut yourself some slack. 
******** revelation: god is in the details, small work is where compounding happens. Continuous work will yield you a no stress life, in the limit. Only when you respect your own schedule will other respect your schedule. You can be elegant and sweet and wonderful even on a busy schedule and people will respect you far more for it. YOu don't have to tell the other person what work it is you are doing. 'I am occupied' will do, really.
******** opportunity: deftly rescheduling is in agreement with 'create longing through absence' principle of Mr Greene.
**** 3 life's tasks: (the book (the courage to be disliked) only talks about three kinds: work, friendship and love, but since I make an effort to not make such distincitons in the interpersonal as friendship and love, I clubbed them into relationships and added the tasks of contributions which now means something to me. Also the book itself says to be happy one needs to feel belonged and to belond one needs to feel like they contribute to a community.
***** tasks of work
***** tasks of relationships
***** tasks of contributions

**** How does one stay averse to inaction?

**** do not seek recognition (The courage to be disliked)
**** don't interrupt the daemon meets optimize for classes. How would they negotiate? 

** .
*** principle-set
**** first rule of the principle set is that you follow your principles
***** follow rules to the core to see where they break, it is a learning process.
***** If it is for a principle, bend a knee, take a loss. But also remember, in the limit, you take no loss; if it appears otherwise, reevaluate your principle set.
**** You cannot pour from an empty pot. Prioritize self's well-being. Sometimes this means you may not be there for someone in need, but when you need yourself you have got to be there for yourself.
**** accountability, and ownership of work. What are the different form it takes in how it is already implemented and how it is not as yet implemented but will be implemented? Are there any places this will not be implemented? Simply stating the answer for the last one is important since it is like an uncomputable problem, even if we do cannot compute it, it is good to know that that is the case.
**** underpromise and overdeliver. Generally followed principle. Where do I not follow it and what does that tell about my relationship with expectations, performance and conformity?
**** long term over short term, in the limit, any day.
***** Hell yeah or no is a way to achieve this.
***** say no to cheap dopamine is subsumed under this paradigm
*****  skeletal muscle is a reservoir of blood glucose [andrew huberman podcast]. it is important to prioritize long term over short term. thus, building and maintaining skeletal muscle is important.
**** humility is a non-negotiable, for it is not for others, it is for your own self. Celebration as a strategy tool is subsumed under this paradigm
humility is among other things a way of emptying the cup of your being, so that there is room for more from the world.
Another form this takes is the absence of celebration as socially dictated. Celebration then becomes a tool, in the form of a reward it is only used to incentivize or reinforce good behavior and as soon as the behaviour start taking root, the reward sees exponential decay so as to take of the training wheels.
**** don't celebrate; celebrate only when
this is in line with dopamine graph and baseline resetting. when you celebrate you are embodying the idea in your dopamine release, that whatever you have done albeit worth desriable is also rare. When something is achieved, while others celebrate, you ought to act with nonchalance and realise that you are now that sort of person that just does this thing that is achieved in a commonplace manner.
celebrate when there is an utter lack of motivation. Do a small achievable task and celebrate it in your dopaminergic way, then this will trigger a cycle of dopamine release and work that will carry you.
**** always only lead by example. To what extent is this followed? Do I ever lead at all? Is it imperative that I lead? What is my relationshiop with the roles of the dynamic with Group/Mob that I am part of 
**** no conspicuous consumption.  What about consumption that is incidentally conspicuous? And the effects that it has on identity in relationship with  conspicuous consumption?
**** stimulus response management
***** molecule of more (cognitive behavioral therapy and Motivational enhancemnt therapy and 12 step facilitation therapy. Abstract away principles from these.) Make the person say the thing you want to tell them so as to make them take ownership of the notion.
***** power of habit, atomic habits, elastic habits, compounding effect.
***** resistance can be stopped from reaching criticality and from compounding
***** cue-stimulus-routine, golden rule of habit change. If you have started a bad routine, the simple way out is to do what would the good routine upon encounting the cue.
***** when there is resistance, reorient your response to the stimulus in whatever capacity you can, upto the point that resistance overwhelms you and no more beyond. This enables you to reproduce the response again next time you encounter the stimulus and over time the resistance will wither away or crumble down. Comes under response-stimulus management.
**** ascetism and no substances
***** endogenic highs and lows only, paleolithic diet, embracing boredom
****** it is important to see the lows through, it builds temperance (and character?)
****** What you do as a response to boredom determines your life to some extent. ~ Dan Koe (youtube productivity guy).
***** Amor Fati. Embrace the moment
***** say no to cheap dopamine. do not sell yourself to pleasure.
***** stillness and silence
**** No one will out-(healthy-)work me.

**** no task-switching (aka multi-tasking)
**** Each new day, earn your own success. Don't live off of yesterday. But save for and invest in tomorrow.
**** meditation and friendship are like insurance. Pay your premiums. 
**** focus on work
**** focus on things in your control; focus on your tasks.
**** Never complain, never explain
never complain that life is a certain way, focus on your work and things in your control. Never explain for saying sorry is not desirable for it makes the dissonance go away, you want the dissonance to stay with you as a negative feedback, never explain your actions, if you are sorry, show it in your future actions by not doing it again, 
never explain yourself, time will show everything to everyone, focus on just doing your work and abiding by your principles.

**** dialogue 
never seek a piece of advice, for advice is a monologic discourse, have a conversation with people to understand what they did or would do, to understand their operating priniciples, in this discourse, there happens a dialogue and through that something useful, such as knowledge or insight, may emerge.
**** systematize for focus and unwavering attention. The devil is in the details
**** sharpen your axe before you swing it. systems-think.
**** don't interrupt the daemon (creative spirit) (daemon as talked about eat pray love author Elizabeth Gilbert in her ted talk). Let the daemon (creative spirit)  interrupt and take over if it were to reach critical moment of clarity of course of action.
**** precedence rules for work
***** Reading up before class >>>(is so much better and desirable than) reading after class
**** Prepone, develop foresight and execute.
A stitch in time saves nine. A stitch well in advance will save nine million.
**** social interface as blog to save energy, time and opportunity cost. Why is this not seeing implementation? I do have a notion page, but is it too disorganized to see the light of social eyes. I have a distribution channel. I am willing to be shameless if I see the results in foresight. Let us chart and remove the resistances
***** disorganized pages
****** This is certainly resolvable. The solution shall take the same form as the solution for the organisation of thought in Linux inode system. 
****** linux: 
******* observations
******** generally I dump a lot of things that are supposed to be readily accessible because they are trinkets in the high level of organization. Making a miscellaneous folder is not desireable because it is a black box that will be visited way to often leading to dissapointment and resentment coloring its name. How do i solve this problem. I contend this is a significant part of the organisation problem. Concerns include access having to correspond to the weight of the file in salience.
******** there are two big things of big salience: t8.org and uni/, a file and a folder
******** this said
********* it also pays to learn the organisation of non-user inodes of the system organisation. 
********* / is the root directory
********** level 1 has a lot of inodes. Things include software, configurations, paths, symbolic links, places for the kernal to write to, and thus also places for the kernal to read from or execute from, places where device drivers are hosted, there are things like binaries what are these things?
********** what is the difference between configuration and paths? What is the entity entity relationship?
******* generally there are two intertwined trees: my thoughts, my software
******** thoughts
********* level 1 : desk/, Documents/, Downloads/, KindleClippings/, Pictures/, scripts/, Templates/, uni/, Uploads/, courses.sh, KindleClippings.py, MyClippings.txt, t8.org, tools.txt, work.sh
********** desk: spreadsheets
********** Documents: codeToLiveBy/, MuseScore3, ObsidianVault/, quotes.csv, thoughts.md
********** Downloads: Books, TechnicalBooks, papers, verse, transcriptsAtKrea, generally books and thoughts and notes on the books
********** KindleClippings
*********** MyClippings.txt
********** Pictures: Screenshots
********** t8.org
********** scritps et al
********** tools.txt
********** work.sh
******** software
********** org-roam, inkscape-shortcut-manager, snap, src (vim, ultisnips), surf, venv, zotero, RMAIL
****** social interface open pages
******* The big things: conversation rooms, recommended prereqs. There is no point in conversation rooms, since everyting is open for comment and interactions. Recommended prerequisites is just a matter of your vanity and is not necessary either, since the whole blog is about recommended prereqs really. Thus, the big things crumble away.
******* the trinkets: thoughts, quotes. The trinkets can just be embellishments. They can be worked into essays.
****** What does organisation look like:
******* facilitator of new ideas. It has an entry point for everything
******* everything is a mini essay, like everything in python is an object.
******* It has to intuitive to navigate, at the same time presenting ideas with salience in order of encounter. This is usually automatically done.
******* There should be no perplexity. Assume an absolute stranger and make it easy to navigate for them.
******* To achieve the above, I need to understand how web pages can be presented. and how indeas can possibly be presented using web pages. 
******** there are layers. You can go deeper and deeper. 
******** What is your audience? To find readership, you dont try to write for anyone. You become great in yourself and accumulate fans. 
******** Who is your author? The author is a compendium of useful things. So there you have it. Just write interesting things.
***** distribution
The primary problem is perhaps in distribution. For distribution to happen, it has to at least be navigable. What about it is not navigable? What does a navigable interface look like?
***** systemic persistance
** ""
** _
